--- !ruby/object:RI::ClassDescription 
attributes: 
- !ruby/object:RI::Attribute 
  comment: 
  name: caller
  rw: W
- !ruby/object:RI::Attribute 
  comment: 
  name: content
  rw: W
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: The options passed to the Sass Engine.
  name: options
  rw: R
- !ruby/object:RI::Attribute 
  comment: 
  name: selector
  rw: W
class_methods: 
- !ruby/object:RI::MethodSummary 
  name: inherited_hash_accessor
- !ruby/object:RI::MethodSummary 
  name: inherited_hash_reader
- !ruby/object:RI::MethodSummary 
  name: inherited_hash_writer
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:SM::Flow::P 
  body: The abstract base class for lexical environments for SassScript.
constants: []

full_name: Sass::BaseEnvironment
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: caller
- !ruby/object:RI::MethodSummary 
  name: content
- !ruby/object:RI::MethodSummary 
  name: global?
- !ruby/object:RI::MethodSummary 
  name: global_env
- !ruby/object:RI::MethodSummary 
  name: selector
- !ruby/object:RI::MethodSummary 
  name: stack
name: BaseEnvironment
superclass: Object
