#!/bin/bash
#
# Fix symbolic links on Windows for the given folder
#
if [ $# -eq 0 ]
  then
    PP=./
  else
   PP=$@
fi
find $PP -type f -size -512c -exec gawk 'FNR==1 && /!<symlink>/ { print FILENAME }; FNR>1 {nextfile}' {} + | sed -e 's/\\/\//g' | xargs -n 1 attrib +s
