--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: An environment that can write to in-scope global variables, but doesn't create new variables in the global scope. Useful for top-level control directives.
constants: []

full_name: Sass::SemiGlobalEnvironment
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: try_set_var
name: SemiGlobalEnvironment
superclass: Environment
