--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: A read-only wrapper for a lexical environment for SassScript.
constants: []

full_name: Sass::ReadOnlyEnvironment
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: caller
- !ruby/object:RI::MethodSummary 
  name: content
name: ReadOnlyEnvironment
superclass: BaseEnvironment
