# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded portimage 2.0 [list source [file join $dir portimage.tcl]]
package ifneeded receipt_flat 1.0 [list source [file join $dir receipt_flat.tcl]]
package ifneeded receipt_sqlite 1.0 [list source [file join $dir receipt_sqlite.tcl]]
package ifneeded registry 1.0 [list source [file join $dir registry.tcl]]\n[list source [file join $dir registry_autoconf.tcl]]
package ifneeded registry2 2.0 [list load [file join $dir registry.dylib]]
package ifneeded registry_uninstall 2.0 [list source [file join $dir portuninstall.tcl]]
package ifneeded registry_util 2.0 [list source [file join $dir registry_util.tcl]]
