#!/bin/sh
if test "z$*" = zversion ||
   test "z$*" = z--version
then
	echo 'git-gui version 0.20.0'
else
	libdir="${GIT_GUI_LIB_DIR:-/Applications/XAMPP/ds-plugins/ds-cli/platform/mac/homebrew/Cellar/git/2.7.0/share/git-gui/lib}"
	exec "$libdir/Git Gui.app/Contents/MacOS/Wish" "$0" "$@"
fi
