--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Extracts the non-string vlaues from an array containing both strings and non-strings. These values are replaced with escape sequences. This can be undone using \{#inject_values}.
- !ruby/struct:SM::Flow::P 
  body: This is useful e.g. when we want to do string manipulation on an interpolated string.
- !ruby/struct:SM::Flow::P 
  body: The precise format of the resulting string is not guaranteed. However, it is guaranteed that newlines and whitespace won't be affected.
- !ruby/struct:SM::Flow::P 
  body: "@param arr [Array] The array from which values are extracted. @return [(String, Array)] The resulting string, and an array of extracted values."
full_name: Sass::Util#extract_values
is_singleton: false
name: extract_values
params: (arr)
visibility: public
